version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITIDB-ROOT_USERNAME: root
      MONGO_INITIDB-ROOT_PASSWORD: password
      MONGO_INITIDB-DATABASE: product-service
    volumes:
      - ./data:/data/db

